# MIT License

# Copyright (c) 2023 Replicable-MARL

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

env: cyborg

env_args:
  map_name: "cage3" # others can be found in cyborg.py
  environment: "sim"
  env_config: null
  agents: null
  seed: null
  drone_swarm_scenario_configuration:
    max_length_data_links: 30
    data_link_bandwidth: 100
    num_drones: 18
    starting_num_red: 0
    starting_positions: null
    default_red_agent: null
    red_spawn_rate: 0.05
    red_internal_only: True
    agent_to_drone_mapping: null
    maximum_steps: 500
    all_external: False

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False
